server:
  port: 9179

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.211.55.3:3306/joine?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 10.211.55.3:5682
      password: root
      username: root
      queue: zipkin
  storage:
    type: mysql
